version: "3"
services:
    api:
        container_name: api
        #network_mode: host
        build: 
            context: ./API/
            #network: host
        ports:
            - 5001:5001
        restart: always
        depends_on: 
            - redis
    monitor:
        container_name: monitor
        #network_mode: host
        build: 
            context: ./Task-Manager/
            #network: host            
        ports:
            - 5555:5555
        entrypoint: flower
        command:  -A tasks --port=5555 --broker=redis://redis:6379/0
        depends_on:
            - redis
    redis:
        container_name: redis
        #network_mode: host
        image: redis
    tf-serving:
        container_name: tf-serving
        #network_mode: host
        image: tensorflow/serving
        command: --model_config_file=/models/models.config
        depends_on:
            - redis
        ports:
            - 8501:8501
        restart: always
        volumes:
            -  //c/development/ML-Toolkit/Tensorflow-Serving/models:/models/
            #-  /home/cristiano/development/ML-Toolkit/Tensorflow-Serving/models:/models/
    worker:
        container_name: worker
        #network_mode: host
        build:
            context: ./Task-Manager/
            dockerfile: Dockerfile
            #network: host
        depends_on:
            - redis
        ports:
            - 5000:5000
    