version: "3"
services:
    server:
        build: ./API/
        ports:
            - 5001:5001
        restart: always
        depends_on: 
            - redis
    monitor:
        build: ./Task-Manager/
        ports:
            - 5555:5555
        entrypoint: flower
        command:  -A tasks --port=5555 --broker=redis://redis:6379/0
        depends_on:
            - redis
    redis:
        image: redis
    tf-serving:
        image: tensorflow/serving
        network_mode: host
        command: --model_config_file=/models/models.config
        depends_on:
            - redis
        ports:
            - 8501:8501
        restart: always
        volumes:
            -  /home/cristiano/development/ML-Toolkit/Tensorflow-Serving/models:/models/
    worker:
        build:
            context: ./Task-Manager/
            dockerfile: Dockerfile
        depends_on:
            - redis